//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Simple.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SimpleParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ISimpleVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] SimpleParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.topLevelItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopLevelItem([NotNull] SimpleParser.TopLevelItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] SimpleParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessModifier([NotNull] SimpleParser.AccessModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnType([NotNull] SimpleParser.ReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] SimpleParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] SimpleParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] SimpleParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.blockItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockItem([NotNull] SimpleParser.BlockItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] SimpleParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] SimpleParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] SimpleParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarator([NotNull] SimpleParser.VariableDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaratorId([NotNull] SimpleParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] SimpleParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseType([NotNull] SimpleParser.BaseTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.arrayDimensions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDimensions([NotNull] SimpleParser.ArrayDimensionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] SimpleParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpression([NotNull] SimpleParser.AssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentTarget([NotNull] SimpleParser.AssignmentTargetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] SimpleParser.AssignmentOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalExpression([NotNull] SimpleParser.ConditionalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrExpression([NotNull] SimpleParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndExpression([NotNull] SimpleParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.bitwiseOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseOrExpression([NotNull] SimpleParser.BitwiseOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.bitwiseXorExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseXorExpression([NotNull] SimpleParser.BitwiseXorExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.bitwiseAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseAndExpression([NotNull] SimpleParser.BitwiseAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpression([NotNull] SimpleParser.EqualityExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] SimpleParser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftExpression([NotNull] SimpleParser.ShiftExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] SimpleParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] SimpleParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] SimpleParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpression([NotNull] SimpleParser.PostfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] SimpleParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] SimpleParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] SimpleParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedName([NotNull] SimpleParser.QualifiedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.arrayCreation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayCreation([NotNull] SimpleParser.ArrayCreationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.arrayCreationDimensions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayCreationDimensions([NotNull] SimpleParser.ArrayCreationDimensionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.arrayDimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDimension([NotNull] SimpleParser.ArrayDimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInitializer([NotNull] SimpleParser.ArrayInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] SimpleParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess([NotNull] SimpleParser.ArrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStatement([NotNull] SimpleParser.PrintStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] SimpleParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] SimpleParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] SimpleParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfBlock([NotNull] SimpleParser.IfBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.whileBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileBlock([NotNull] SimpleParser.WhileBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.forBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForBlock([NotNull] SimpleParser.ForBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInit([NotNull] SimpleParser.ForInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.variableDeclarationNoSemicolon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarationNoSemicolon([NotNull] SimpleParser.VariableDeclarationNoSemicolonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.forUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForUpdate([NotNull] SimpleParser.ForUpdateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.forEachBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachBlock([NotNull] SimpleParser.ForEachBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.doWhileBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhileBlock([NotNull] SimpleParser.DoWhileBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.switchBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchBlock([NotNull] SimpleParser.SwitchBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.switchCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchCase([NotNull] SimpleParser.SwitchCaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.defaultCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultCase([NotNull] SimpleParser.DefaultCaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] SimpleParser.LiteralContext context);
}
